/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const get_current_month: () => number;
export const get_month_name: (a: number, b: number, c: number) => [number, number, number, number];
export const get_month_name_async: (a: number, b: number, c: number) => any;
export const get_month_names_all: (a: number) => [number, number, number];
export const get_japanese_month_name: (a: number) => [number, number];
export const get_english_month_name: (a: number) => [number, number];
export const get_ukrainian_month_name: (a: number) => [number, number];
export const get_ukrainian_alphabet_month_name: (a: number) => [number, number];
export const get_swedish_month_name: (a: number) => [number, number];
export const get_suomi_month_name: (a: number) => [number, number];
export const get_polish_month_name: (a: number) => [number, number];
export const get_czech_month_name: (a: number) => [number, number];
export const get_slovak_month_name: (a: number) => [number, number];
export const get_lithuanian_month_name: (a: number) => [number, number];
export const get_latvian_month_name: (a: number) => [number, number];
export const get_estonian_month_name: (a: number) => [number, number];
export const __wbg_jserror_free: (a: number, b: number) => void;
export const jserror_new: (a: number, b: number) => number;
export const jserror_message: (a: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_export_3: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const closure27_externref_shim: (a: number, b: number, c: any) => void;
export const closure39_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
